#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

app_blog:
  path: /blog
  controller: App\Controller\BlogController::index

app_index:
  path: /default
  controller: App\Controller\DefaultController::index
